from selenium import webdriver
from selenium.webdriver.support.ui import Select
import time
from selenium.webdriver.common.alert import Alert
url = 'http://103.8.112.44/hrms_ui/'
path = 'C:\driver/chromedriver.exe'

driver = webdriver.Chrome(path)
driver.get(url)
time.sleep(5)


driver.maximize_window()

form = driver.find_element_by_xpath('//form[@name="form"]')
username = form.find_element_by_xpath('//input[@id="username"]')
password = form.find_element_by_xpath('//input[@id="password"]')
username.send_keys("IAI000052")
password.send_keys("12345")
time.sleep(1)
login = form.find_element_by_xpath('//button[@type="submit"]')
login.click()
time.sleep(1)

sidebar = driver.find_element_by_xpath('//a[@class="sidebar-toggle"]')
sidebar.click()
time.sleep(1)
clickon = driver.find_element_by_xpath('//*[@id="menulist"]/li[7]/a')
clickon.click()
AR = driver.find_element_by_xpath('//*[@id="menulist"]/li[7]/ul/li[1]/a')
AR.click()
time.sleep(1)
formdate = driver.find_element_by_xpath('//*[@id="datepicker4"]')
formdate.send_keys('02/20/2022')
time.sleep(1)
todate = driver.find_element_by_xpath('//*[@id="datepicker5"]')
todate.send_keys('03/10/2022')
time.sleep(1)
employee = driver.find_element_by_xpath('//*[@id="form-emp"]')
employee.click()
employee.send_keys('Zeeshan Ahmad')
time.sleep(1)
dpt = driver.find_element_by_xpath('//*[@id="department"]')
dpt.click()
dpt.send_keys('Implementations')
time.sleep(1)
submit = driver.find_element_by_xpath('//*[@id="btn_submit"]')
submit.click()
time.sleep(1)
driver.execute_script("window.scrollBy(0,300)","")
time.sleep(2)
filter = driver.find_element_by_xpath('//*[@id="requesttbl_length"]/label/select')
filter.click()
filter.send_keys('25')
time.sleep(1)
search = driver.find_element_by_xpath('//*[@id="requesttbl_filter"]/label/input')
search.click()
search.send_keys('2022-02-22')
time.sleep(1)
export = driver.find_element_by_xpath('//*[@id="exportreport"]')
export.click()
time.sleep(1)
sidebar = driver.find_element_by_xpath('//a[@class="sidebar-toggle"]')
sidebar.click()
time.sleep(1)
clickon = driver.find_element_by_xpath('//*[@id="menulist"]/li[7]/a')
clickon.click()
time.sleep(1)
BM = driver.find_element_by_xpath('//*[@id="menulist"]/li[7]/ul/li[2]/a')
BM.click()
time.sleep(1)
formdate = driver.find_element_by_xpath('//*[@id="from_date"]')
formdate.send_keys('02/20/2022')
time.sleep(1)
todate = driver.find_element_by_xpath('//*[@id="to_date"]')
todate.send_keys('03/01/2022')
time.sleep(1)
employee = driver.find_element_by_xpath('//*[@id="form-emp"]')
employee.click()
employee.send_keys('Zeeshan Ahmad')
time.sleep(1)
dpt = driver.find_element_by_xpath('//*[@id="department"]')
dpt.click()
dpt.send_keys('Implementations')
time.sleep(1)
submit = driver.find_element_by_xpath('//*[@id="btn_submit"]')
submit.click()
time.sleep(1)
driver.execute_script("window.scrollBy(0,500)","")
time.sleep(2)
show = driver.find_element_by_xpath('//*[@id="requesttbl_length"]/label/select')
show.click()
show.send_keys('25')
time.sleep(1)
search = driver.find_element_by_xpath('//*[@id="requesttbl_filter"]/label/input')
search.click()
search.send_keys('02/25/2022')
time.sleep(1)
export = driver.find_element_by_xpath('//*[@id="exportreport"]')
export.click()
time.sleep(1)
sidebar = driver.find_element_by_xpath('//a[@class="sidebar-toggle"]')
sidebar.click()
time.sleep(1)
sidebar = driver.find_element_by_xpath('//a[@class="sidebar-toggle"]')
sidebar.click()
clickon = driver.find_element_by_xpath('//*[@id="menulist"]/li[7]/a')
clickon.click()
time.sleep(1)
lm = driver.find_element_by_xpath('//*[@id="menulist"]/li[7]/ul/li[3]/a')
lm.click()
time.sleep(1)
fordate = driver.find_element_by_xpath('//*[@id="form_from"]')
fordate.send_keys('02/20/2022')
time.sleep(1)
todate = driver.find_element_by_xpath('//*[@id="form_to"]')
todate.send_keys('03/10/2022')
time.sleep(1)
employee = driver.find_element_by_xpath('//*[@id="form-emp"]')
employee.click()
employee.send_keys('Zeeshan Ahmad')
time.sleep(1)
dpt = driver.find_element_by_xpath('//*[@id="department"]')
dpt.click()
dpt.send_keys('Implementations')
time.sleep(1)
submit = driver.find_element_by_xpath('//*[@id="btn_submit"]')
submit.click()
time.sleep(1)
driver.execute_script("window.scrollBy(0,500)","")
time.sleep(2)
show = driver.find_element_by_xpath('//*[@id="requesttbl_length"]/label/select')
show.click()
show.send_keys('50')
time.sleep(1)
search = driver.find_element_by_xpath('//*[@id="requesttbl_filter"]/label/input')
search.click()
search.send_keys('03/01/2022')
time.sleep(1)
export = driver.find_element_by_xpath('//*[@id="btn_export"]')
export.click()
time.sleep(1)
sidebar = driver.find_element_by_xpath('//a[@class="sidebar-toggle"]')
sidebar.click()
clickon = driver.find_element_by_xpath('//*[@id="menulist"]/li[7]/a')
clickon.click()
time.sleep(1)
ot = driver.find_element_by_xpath('//*[@id="menulist"]/li[7]/ul/li[4]/a')
ot.click()
time.sleep(1)
formdate = driver.find_element_by_xpath('//*[@id="form-from"]')
formdate.send_keys('02/20/2022')
time.sleep(1)
todate = driver.find_element_by_xpath('//*[@id="form-to"]')
todate.send_keys('03/01/2022')
time.sleep(1)
employee = driver.find_element_by_xpath('//*[@id="form-emp"]')
employee.click()
employee.send_keys('Zeeshan Ahmad')
time.sleep(1)
dpt = driver.find_element_by_xpath('//*[@id="department"]')
dpt.click()
dpt.send_keys('Implementations')
time.sleep(1)
submit = driver.find_element_by_xpath('//*[@id="btn_submit"]')
submit.click()
time.sleep(1)
driver.execute_script("window.scrollBy(0,300)","")
time.sleep(2)
export = driver.find_element_by_xpath('//*[@id="exportreport"]')
export.click()
time.sleep(1)
sidebar = driver.find_element_by_xpath('//a[@class="sidebar-toggle"]')
sidebar.click()
clickon = driver.find_element_by_xpath('//*[@id="menulist"]/li[7]/a')
clickon.click()
time.sleep(1)
sm = driver.find_element_by_xpath('//*[@id="menulist"]/li[7]/ul/li[5]/a')
sm.click()
time.sleep(1)
# manage = driver.find_element_by_xpath('//*[@id="employee_shift"]')
# manage.click()
# manage.send_keys('Zeeshan Ahmad')
# manage.click()
# time.sleep(1)
# workinghour = driver.find_element_by_xpath('//*[@id="shift_from"]')
# workinghour.send_keys('06:13')
# workinghour.send_keys('PM')
# time.sleep(1)
# shifttime = driver.find_element_by_xpath('//*[@id="shift_to"]')
# shifttime.send_keys('12:21')
# shifttime.send_keys('PM')
# shifttime.click()
# time.sleep(1)
# shiftdate  = driver.find_element_by_xpath('//*[@id="datepicker4"]')
# shiftdate.send_keys('03/01/2022')
# time.sleep(1)
# comnts = driver.find_element_by_xpath('//*[@id="cmttextare"]')
# comnts.click()
# comnts.send_keys('qwertyhgdgvcdf')
# time.sleep(1)
# close = driver.find_element_by_xpath('//*[@id="btn_close"]')
# close.click()
# time.sleep(1)
formdate = driver.find_element_by_xpath('//*[@id="form-from"]')
formdate.send_keys('02/20/2022')
time.sleep(1)
todate = driver.find_element_by_xpath('//*[@id="form-to"]')
todate.send_keys('03/01/2022')
time.sleep(1)
employee = driver.find_element_by_xpath('//*[@id="form-emp"]')
employee.click()
employee.send_keys('Zeeshan Ahmad')
time.sleep(1)
dpt = driver.find_element_by_xpath('//*[@id="department"]')
dpt.click()
dpt.send_keys('Implementations')
time.sleep(1)
submit = driver.find_element_by_xpath('//*[@id="btn_submit"]')
submit.click()
time.sleep(1)
driver.execute_script("window.scrollBy(0,800)","")
time.sleep(2)
show = driver.find_element_by_xpath('//*[@id="requesttbl_length"]/label/select')
show.click()
show.send_keys('25')
time.sleep(1)
search = driver.find_element_by_xpath('//*[@id="requesttbl_filter"]/label/input')
search.click()
search.send_keys('02/20/2022')
time.sleep(1)
export = driver.find_element_by_xpath('//*[@id="exportreport"]')
export.click()
time.sleep(1)
sidebar = driver.find_element_by_xpath('//a[@class="sidebar-toggle"]')
sidebar.click()
clickon = driver.find_element_by_xpath('//*[@id="menulist"]/li[7]/a')
clickon.click()
time.sleep(1)
AS = driver.find_element_by_xpath('//*[@id="menulist"]/li[7]/ul/li[6]/a')
AS.click()
time.sleep(1)
formdate = driver.find_element_by_xpath('//*[@id="form_from"]')
formdate.send_keys('02/20/2022')
time.sleep(1)
todate = driver.find_element_by_xpath('//*[@id="to_from"]')
todate.send_keys('03/01/2022')
time.sleep(1)
employee = driver.find_element_by_xpath('//*[@id="form-emp"]')
employee.click()
employee.send_keys('Zeehan Ahmad')
time.sleep(1)
dpt = driver.find_element_by_xpath('//*[@id="department"]')
dpt.click()
dpt.send_keys('Implementations')
time.sleep(1)
submit = driver.find_element_by_xpath('//*[@id="btn_submit"]')
submit.click()
time.sleep(1)
driver.execute_script("window.scrollBy(0,800)","")
time.sleep(2)
show = driver.find_element_by_xpath('//*[@id="requesttbl_length"]/label/select')
show.click()
show.send_keys('25')
time.sleep(1)
search = driver.find_element_by_xpath('//*[@id="requesttbl_filter"]/label/input')
search.click()
search.send_keys('2022-02-01')
time.sleep(1)
export = driver.find_element_by_xpath('//*[@id="exportreport"]')
export.click()
time.sleep(1)
home = driver.find_element_by_xpath('/html/body/div/div[1]/section[1]/ol/li[1]/a')
home.click()
time.sleep(1)
