from selenium import webdriver
from selenium.webdriver.support.ui import Select
import time
from selenium.webdriver.common.alert import Alert

url = 'http://103.8.112.44/hrms_ui'
path = 'C:\driver/chromedriver.exe'

driver = webdriver.Chrome(path)
driver.get(url)
time.sleep(5)


driver.maximize_window()

form = driver.find_element_by_xpath('//form[@name="form"]')
username = form.find_element_by_xpath('//input[@id="username"]')
password = form.find_element_by_xpath('//input[@id="password"]')
username.send_keys("IAI000052")
password.send_keys("12345")
time.sleep(1)
login = form.find_element_by_xpath('//button[@type="submit"]')
login.click()
time.sleep(1)
sidebar = driver.find_element_by_xpath('/html/body/div/header/nav/a')
sidebar.click()
time.sleep(1)
dept = driver.find_element_by_xpath('//*[@id="menulist"]/li[4]/a')
dept.click()
time.sleep(1)
createdpt = driver.find_element_by_xpath('//*[@id="menulist"]/li[4]/ul/li[1]/a')
createdpt.click()
time.sleep(1)
dptname = driver.find_element_by_xpath('//*[@id="Name"]')
dptname.click()
dptname.send_keys('Production-Demo')
dptname.click()
time.sleep(1)
director = driver.find_element_by_xpath('//*[@id="director"]')
director.click()
director.send_keys('Qiran Sohail')
director.click()
time.sleep(1)
selectmanager = driver.find_element_by_xpath('//*[@id="manager"]')
selectmanager.click()
selectmanager.send_keys('Subaina Javaid')
selectmanager.click()
time.sleep(1)
pho =driver.find_element_by_xpath('//input[@id="Phone"]')
pho.click()
pho.send_keys('03211234567')
time.sleep(1)
email = driver.find_element_by_xpath('//*[@id="Email"]')
email.send_keys('production@intersoftbpo.com')
time.sleep(1)
address = driver.find_element_by_xpath('//*[@id="Address"]')
address.send_keys('Barket-Market-Lahore')
time.sleep(1)
submit = driver.find_element_by_xpath('//*[@id="btn_submit"]')
submit.click()
time.sleep(5)
sidebar = driver.find_element_by_xpath('/html/body/div/header/nav/a')
sidebar.click()
time.sleep(1)
dept = driver.find_element_by_xpath('//*[@id="menulist"]/li[4]/a')
dept.click()
time.sleep(1)
viewdpt = driver.find_element_by_xpath('//*[@id="menulist"]/li[4]/ul/li[2]/a')
viewdpt.click()
time.sleep(1)
decending = driver.find_element_by_xpath('//*[@id="manageHRMSTable_wrapper"]/div[2]/div[1]/div/table/thead/tr/th[1]')
decending.click()
time.sleep(1)
search = driver.find_element_by_xpath('//*[@id="manageHRMSTable_filter"]/label/input')
search.click()
search.send_keys('63')
time.sleep(1)
edit = driver.find_element_by_xpath('//*[@id="manageHRMSTable"]/tbody/tr[1]/td[10]/a/span')
edit.click()
time.sleep(1)
savechanges = driver.find_element_by_xpath('//*[@id="updateDepartmentForm"]/div[2]/button[2]')
savechanges.click()
time.sleep(1)
search = driver.find_element_by_xpath('//*[@id="manageHRMSTable_filter"]/label/input')
search.click()
search.send_keys('63')
time.sleep(1)
export = driver.find_element_by_xpath('//*[@id="sec1"]/div/div[1]/a')
export.click()
time.sleep(1)
##########################designation################################
sidebar = driver.find_element_by_xpath('/html/body/div/header/nav/a')
sidebar.click()
time.sleep(1)
designation = driver.find_element_by_xpath('//*[@id="menulist"]/li[6]/a')
designation.click()
time.sleep(1)
create = driver.find_element_by_xpath('//*[@id="menulist"]/li[6]/ul/li[1]/a')
create.click()
time.sleep(1)
designationame = driver.find_element_by_xpath('//*[@id="Name"]')
designationame.click()
designationame.send_keys('Production-intern-Demo')
time.sleep(1)
submit = driver.find_element_by_xpath('//*[@id="btn_submit"]')
submit.click()
time.sleep(5)
sidebar = driver.find_element_by_xpath('/html/body/div/header/nav/a')
sidebar.click()
time.sleep(1)
designation = driver.find_element_by_xpath('//*[@id="menulist"]/li[6]/a')
designation.click()
time.sleep(1)
view = driver.find_element_by_xpath('//*[@id="menulist"]/li[6]/ul/li[2]/a')
view.click()
time.sleep(1)
decending = driver.find_element_by_xpath('//*[@id="manageHRMSTable_wrapper"]/div[2]/div[1]/div/table/thead/tr/th[1]')
decending.click()
time.sleep(1)
search = driver.find_element_by_xpath('//*[@id="manageHRMSTable_filter"]/label/input')
search.click()
search.send_keys('Production-intern-Demo')
time.sleep(1)
export = driver.find_element_by_xpath('//*[@id="sec1"]/div/div[1]/a')
export.click()
time.sleep(1)
edit = driver.find_element_by_xpath('//*[@id="manageHRMSTable"]/tbody/tr/td[5]/a[1]')
edit.click()
time.sleep(1)
designationame = driver.find_element_by_xpath('//*[@id="d_name"]').clear()
designationame = driver.find_element_by_xpath('//*[@id="d_name"]')
designationame.click()
designationame.send_keys('Production-intern-DEMO')
time.sleep(1)
savechanges = driver.find_element_by_xpath('//*[@id="updateDesignationForm"]/div[2]/button[2]')
savechanges.click()
time.sleep(1)
search = driver.find_element_by_xpath('//*[@id="manageHRMSTable_filter"]/label/input')
search.click()
search.send_keys('Production-intern-DEMO')
time.sleep(1)
export = driver.find_element_by_xpath('//*[@id="sec1"]/div/div[1]/a')
export.click()
time.sleep(3)
home = driver.find_element_by_xpath('/html/body/div/div[1]/section[1]/ol/li[1]/a')
home.click()
