from selenium import webdriver
from selenium.webdriver.support.ui import Select
import time
from selenium.webdriver.common.alert import Alert
from selenium.webdriver.common.keys import Keys

url = 'http://103.8.112.44/hrms_ui/'
path = 'C:\driver/chromedriver.exe'

driver = webdriver.Chrome(path)
driver.get(url)
time.sleep(5)


driver.maximize_window()

form = driver.find_element_by_xpath('//form[@name="form"]')
username = form.find_element_by_xpath('//input[@id="username"]')
password = form.find_element_by_xpath('//input[@id="password"]')
username.send_keys("IAI000052")
password.send_keys("12345")
time.sleep(1)
login = form.find_element_by_xpath('//button[@type="submit"]')
login.click()
time.sleep(1)
sidebar = driver.find_element_by_xpath('//a[@class="sidebar-toggle"]')
sidebar.click()
time.sleep(1)
event = driver.find_element_by_xpath('//*[@id="menulist"]/li[10]/a')
event.click()
time.sleep(1)
create = driver.find_element_by_xpath('//*[@id="menulist"]/li[10]/ul/li[1]/a')
create.click()
time.sleep(0)
eventname = driver.find_element_by_xpath('//*[@id="event_name"]')
eventname.click()
eventname.send_keys('fesitvel-Demo')
time.sleep(1)
eventdescrip = driver.find_element_by_xpath('//*[@id="description"]')
eventdescrip.send_keys('it will be held on within org(demo)')
time.sleep(1)
fromdate = driver.find_element_by_xpath('//*[@id="from_date"]')
fromdate.send_keys('03/27/00202212:00PM')
time.sleep(1)
todate = driver.find_element_by_xpath('//*[@id="to_date"]')
todate.send_keys('03/27/00202211:00PM')
time.sleep(1)
submit = driver.find_element_by_xpath('//*[@id="btn_submit"]')
submit.click()
time.sleep(1)
# sidebar = driver.find_element_by_xpath('//a[@class="sidebar-toggle"]')
# sidebar.click()
# time.sleep(1)
event = driver.find_element_by_xpath('//*[@id="menulist"]/li[10]/a')
event.click()
time.sleep(1)
view = driver.find_element_by_xpath('//a[@href="http://103.8.112.44/hrms_ui/event/view"]')
view.click()
time.sleep(1)
fromdate = driver.find_element_by_xpath('//*[@id="from_date"]')
fromdate.send_keys('03/27/2022')
time.sleep(1)
todate = driver.find_element_by_xpath('//*[@id="to_date"]')
todate.send_keys('03/27/2022')
time.sleep(1)
submit = driver.find_element_by_xpath('//*[@id="btn_search"]')
submit.click()
time.sleep(1)
home = driver.find_element_by_xpath('/html/body/div/div[1]/section[1]/ol/li[1]/a')
home.click()
time.sleep(1)
