from selenium import webdriver
from selenium.webdriver.support.ui import Select
import time
from selenium.webdriver.common.alert import Alert
from selenium.webdriver.common.keys import Keys

url = 'http://103.8.112.44/hrms_ui/'
path = 'C:\driver/chromedriver.exe'

driver = webdriver.Chrome(path)
driver.get(url)
time.sleep(5)


driver.maximize_window()

form = driver.find_element_by_xpath('//form[@name="form"]')
username = form.find_element_by_xpath('//input[@id="username"]')
password = form.find_element_by_xpath('//input[@id="password"]')
username.send_keys("IAI000052")
password.send_keys("12345")
time.sleep(1)
login = form.find_element_by_xpath('//button[@type="submit"]')
login.click()
time.sleep(1)
sidebar = driver.find_element_by_xpath('//a[@class="sidebar-toggle"]')
sidebar.click()
time.sleep(1)
driver.execute_script("window.scrollBy(0,500)","")
time.sleep(2)
ticket = driver.find_element_by_xpath('//*[@id="menulist"]/li[13]/a')
ticket.click()
time.sleep(1)
ticket = driver.find_element_by_xpath('//*[@id="menulist"]/li[13]/ul/li[1]/a')
ticket.click()
time.sleep(1)
issuetype = driver.find_element_by_xpath('//*[@id="issue_type"]')
issuetype.click()
issuetype.send_keys('Broken Items Issue - Admin')
issuetype.click()
time.sleep(1)
status = driver.find_element_by_xpath('//*[@id="status"]')
status.click()
status.send_keys('Pending ')
status.click()
time.sleep(1)
comnts = driver.find_element_by_xpath('//*[@id="description"]')
comnts.click()
comnts.send_keys('it is only for Testin')
time.sleep(1)
submit = driver.find_element_by_xpath('//*[@id="btn_submit"]')
submit.click()
time.sleep(5)
search = driver.find_element_by_xpath('//*[@id="issue_search"]')
search.click()
search.send_keys('Broken Items Issue - Admin')
search.click()
time.sleep(1)
find = driver.find_element_by_xpath('//*[@id="btn_search"]')
find.click()
time.sleep(5)
decending = driver.find_element_by_xpath('//*[@id="manageAQMSTable_wrapper"]/div[2]/div[1]/div/table/thead/tr/th[1]')
decending.click()
time.sleep(1)
search = driver.find_element_by_xpath('//*[@id="manageAQMSTable_filter"]/label/input')
search.click()
search.send_keys('441')
time.sleep(1)
reopen = driver.find_element_by_xpath('//*[@id="manageAQMSTable"]/tbody/tr[1]/td[11]/a/span')
reopen.click()
time.sleep(1)
comnts = driver.find_element_by_xpath('//*[@id="req_comment_IT"]')
comnts.click()
comnts.send_keys('only for testing purpose')
time.sleep(1)
submit = driver.find_element_by_xpath('//*[@id="editUser"]/div[2]/button[2]')
submit.click()
time.sleep(1)
sidebar = driver.find_element_by_xpath('//a[@class="sidebar-toggle"]')
sidebar.click()
time.sleep(1)
driver.execute_script("window.scrollBy(0,500)","")
time.sleep(2)
ticket = driver.find_element_by_xpath('//*[@id="menulist"]/li[13]/a')
ticket.click()
time.sleep(1)
history = driver.find_element_by_xpath('//*[@id="menulist"]/li[13]/ul/li[2]/a')
history.click()
time.sleep(1)
fromdate = driver.find_element_by_xpath('//*[@id="datepicker4"]')
fromdate.send_keys('02/21/2022')
time.sleep(1)
todate = driver.find_element_by_xpath('//*[@id="datepicker5"]')
todate.send_keys('02/26/2022')
time.sleep(1)
ticket = driver.find_element_by_xpath('//*[@id="ticket_no"]')
ticket.send_keys('867177')
time.sleep(1)
submit = driver.find_element_by_xpath('//*[@id="btn_submit"]')
submit.click()
time.sleep(1)
search = driver.find_element_by_xpath('//*[@id="manageAQMSTable_filter"]/label/input')
search.click()
search.send_keys('867177')
time.sleep(1)
export = driver.find_element_by_xpath('//*[@id="btn_export"]')
export.click()
time.sleep(1)











setting = driver.find_element_by_xpath('/html/body/div/header/nav/div[1]/ul/li[2]/a')
setting.click()
time.sleep(1)
setting = driver.find_element_by_xpath('/html/body/div/header/nav/div[1]/ul/li[2]/a')
setting.click()
time.sleep(1)
home = driver.find_element_by_xpath('/html/body/div/div[1]/section[1]/ol/li[1]/a')
home.click()
time.sleep(1)
