from selenium import webdriver
from selenium.webdriver.support.ui import Select
import time
from selenium.webdriver.common.alert import Alert
from selenium.webdriver.common.keys import Keys

url = 'http://103.8.112.44/hrms_ui/'
path = 'C:\driver/chromedriver.exe'

driver = webdriver.Chrome(path)
driver.get(url)
time.sleep(5)


driver.maximize_window()

form = driver.find_element_by_xpath('//form[@name="form"]')
username = form.find_element_by_xpath('//input[@id="username"]')
password = form.find_element_by_xpath('//input[@id="password"]')
username.send_keys("IAI000052")
password.send_keys("12345")
time.sleep(1)
login = form.find_element_by_xpath('//button[@type="submit"]')
login.click()
time.sleep(1)
sidebar = driver.find_element_by_xpath('//a[@class="sidebar-toggle"]')
sidebar.click()
time.sleep(1)
ticker = driver.find_element_by_xpath('//*[@id="menulist"]/li[11]/a')
ticker.click()
createview = driver.find_element_by_xpath('//*[@id="menulist"]/li[11]/ul/li/a')
createview.click()
write = driver.find_element_by_xpath('//*[@id="form-description"]')
write.click()
write.send_keys('PSL(Demo)')
time.sleep(1)
internal = driver.find_element_by_xpath('//*[@id="int"]')
internal.click()
time.sleep(1)
external = driver.find_element_by_xpath('//*[@id="ext"]')
external.click()
time.sleep(1)
link = driver.find_element_by_xpath('//*[@id="form-link"]')
link.click()
link.send_keys('https://propakistani.pk/psl-2022/live-streaming/')
time.sleep(1)
dpt = driver.find_element_by_xpath('//*[@id="form-dept"]')
dpt.click()
dpt.send_keys('Production-Demo')
time.sleep(1)
submit = driver.find_element_by_xpath('//*[@id="btn_submit"]')
submit.click()
time.sleep(10)
searchticker = driver.find_element_by_xpath('//*[@id="form-linktype"]')
searchticker.click()
searchticker.send_keys('External')
searchticker.click()
time.sleep(1)
find = driver.find_element_by_xpath('//*[@id="btn_search"]')
find.click()
search = driver.find_element_by_xpath('//*[@id="manageHRMSTable_filter"]/label/input')
search.click()
search.send_keys('56')
time.sleep(1)
edit = driver.find_element_by_xpath('//*[@id="manageHRMSTable"]/tbody/tr/td[7]/a[1]/span')
edit.click()
time.sleep(1)
decription = driver.find_element_by_xpath('//*[@id="t_desc"]').clear()
decription = driver.find_element_by_xpath('//*[@id="t_desc"]')
decription.click()
decription.send_keys('PSL-7!-MATCH-DEMO')
time.sleep(1)
link = driver.find_element_by_xpath('//*[@id="t_link"]').click()
link = driver.find_element_by_xpath('//*[@id="t_link"]').clear()
link = driver.find_element_by_xpath('//*[@id="t_link"]')
link.click()
link.send_keys('https://propakistani.pk/psl-2022/live-streaming/')
time.sleep(1)
link.click()
time.sleep(1)
linktype = driver.find_element_by_xpath('//*[@id="t_linktype"]')
linktype.click
linktype.send_keys('Internal')
linktype.click()
time.sleep(3)
linktype = driver.find_element_by_xpath('//*[@id="t_linktype"]')
linktype.click()
linktype.send_keys('External')
linktype.click()
time.sleep(1)
status = driver.find_element_by_xpath('//*[@id="t_status"]')
status.click()
status.send_keys('InActive')
time.sleep(3)
status = driver.find_element_by_xpath('//*[@id="t_status"]')
status.click()
status.send_keys('Active')
time.sleep(1)
savechanges = driver.find_element_by_xpath('//*[@id="editUser"]/div[2]/button[2]')
savechanges.click()
time.sleep(5)
searchticker = driver.find_element_by_xpath('//*[@id="form-linktype"]')
searchticker.click()
searchticker.send_keys('External')
searchticker.click()
time.sleep(1)
find = driver.find_element_by_xpath('//*[@id="btn_search"]')
find.click()
search = driver.find_element_by_xpath('//*[@id="manageHRMSTable_filter"]/label/input')
search.click()
search.send_keys('56')
time.sleep(1)
setting = driver.find_element_by_xpath('/html/body/div/header/nav/div[1]/ul/li[2]/a')
setting.click()
time.sleep(1)
setting = driver.find_element_by_xpath('/html/body/div/header/nav/div[1]/ul/li[2]/a')
setting.click()
time.sleep(1)
home = driver.find_element_by_xpath('/html/body/div/div[1]/section[1]/ol/li[1]/a')
home.click()
time.sleep(1)



#########internal##################

sidebar = driver.find_element_by_xpath('//a[@class="sidebar-toggle"]')
sidebar.click()
time.sleep(1)
ticker = driver.find_element_by_xpath('//*[@id="menulist"]/li[11]/a')
ticker.click()
createview = driver.find_element_by_xpath('//*[@id="menulist"]/li[11]/ul/li/a')
createview.click()
write = driver.find_element_by_xpath('//*[@id="form-description"]')
write.click()
write.send_keys('PSL-demo')
time.sleep(1)
internal = driver.find_element_by_xpath('//*[@id="int"]')
internal.click()
time.sleep(1)
dpt = driver.find_element_by_xpath('//*[@id="form-dept"]')
dpt.click()
dpt.send_keys('Implementations')
time.sleep(1)
submit = driver.find_element_by_xpath('//*[@id="btn_submit"]')
submit.click()
time.sleep(10)
searchticker = driver.find_element_by_xpath('//*[@id="form-linktype"]')
searchticker.click()
searchticker.send_keys('Internal')
searchticker.click()
time.sleep(1)
find = driver.find_element_by_xpath('//*[@id="btn_search"]')
find.click()
# edit = driver.find_element_by_xpath('//*[@id="manageHRMSTable"]/tbody/tr/td[7]/a[1]/span')
# edit.click()
# time.sleep(1)
# decription = driver.find_element_by_xpath('//*[@id="t_desc"]').clear()
# decription = driver.find_element_by_xpath('//*[@id="t_desc"]')
# decription.click()
# decription.send_keys('PSL-7!-MATCH-DEMO')
# time.sleep(1)
# link = driver.find_element_by_xpath('//*[@id="t_link"]').click()
# link = driver.find_element_by_xpath('//*[@id="t_link"]').clear()
# link = driver.find_element_by_xpath('//*[@id="t_link"]')
# link.click()
# link.send_keys('https://propakistani.pk/psl-2022/live-streaming/')
# time.sleep(1)
# link.click()
# time.sleep(1)
# linktype = driver.find_element_by_xpath('//*[@id="t_linktype"]')
# linktype.click
# linktype.send_keys('Internal')
# linktype.click()
# time.sleep(3)
# linktype = driver.find_element_by_xpath('//*[@id="t_linktype"]')
# linktype.click()
# linktype.send_keys('Internal')
# linktype.click()
# time.sleep(1)
# status = driver.find_element_by_xpath('//*[@id="t_status"]')
# status.click()
# status.send_keys('InActive')
# time.sleep(3)
# status = driver.find_element_by_xpath('//*[@id="t_status"]')
# status.click()
# status.send_keys('Active')
# time.sleep(1)
# savechanges = driver.find_element_by_xpath('//*[@id="editUser"]/div[2]/button[2]')
# savechanges.click()
# time.sleep(5)
# searchticker = driver.find_element_by_xpath('//*[@id="form-linktype"]')
# searchticker.click()
# searchticker.send_keys('Internal')
# searchticker.click()
# time.sleep(1)
# find = driver.find_element_by_xpath('//*[@id="btn_search"]')
# find.click()
# decending = driver.find_element_by_xpath('//*[@id="manageHRMSTable_wrapper"]/div[2]/div[1]/div/table/thead/tr/th[1]')
# decending.click()
# time.sleep(1)
search = driver.find_element_by_xpath('//*[@id="manageHRMSTable_filter"]/label/input')
search.click()
search.send_keys('61')
time.sleep(1)
setting = driver.find_element_by_xpath('/html/body/div/header/nav/div[1]/ul/li[2]/a')
setting.click()
time.sleep(1)
home = driver.find_element_by_xpath('/html/body/div/div[1]/section[1]/ol/li[1]/a')
home.click()
time.sleep(1)
setting = driver.find_element_by_xpath('/html/body/div/header/nav/div[1]/ul/li[2]/a')
setting.click()
time.sleep(1)
logout = driver.find_element_by_xpath('/html/body/div/header/nav/div[1]/ul/li[2]/ul/li[3]/a')
logout.click()
time.sleep(5)

home = driver.find_element_by_xpath('/html/body/div/div[1]/section[1]/ol/li[1]/a')
home.click()
time.sleep(1)